### ISSUE TITLE
Please add "run" shell scripts to examples/pipelines folder

### ISSUE THREAD

**Issue by barryhicks** [kyocum/disdat#10]
Can we please add a "run" shell script to each example py file in examples/pipelines?

For example, for "ExamplePipeline.py" mentioned in the previous issue, we would add a "run_ExamplePipeline.sh" shell script, with the following contents:

dsdt apply - average ExamplePipeline.Average

Having the run scripts is really helpful for a new person, rather than having to guess at what the apply parameters should be for each py script.

**Comment by kyocum** [comment]
Just added example scripts in examples/demo/demo_{first,second}.sh  

And added example as demo_example.py in examples/pipelines.py
