### ISSUE TITLE
Can't run through tutorial steps successfully

### ISSUE THREAD

**Issue by stefano-meschiari** [kyocum/disdat#100]
I took `dsdt` for a quick spin and tried to run the Short Test Drive instructions. I've followed the `mkvirtualenv/git clone` instructions on my local Mac, then tried it in a Docker container to make it easier to reproduce:

```
# disdat Dockerfile
FROM python:3
RUN pip install disdat
RUN pip install awscli
```

```
$ docker run --rm -it -v $PWD:/disdat -t disdat /bin/bash
# dsdt init
# dsdt context mycontext
Disdat created data context None/mycontext at object dir /root/.disdat/context/mycontext/objects.
# dsdt switch mycontext
Switched to context mycontext
# dsdt add my.first.bundle /disdat/examples/hello_data.csv
disdat.api.Register: Source file /usr/local/lib/python3.7/site-packages/luigi/task_register.py not under git version control
# dsdt ls -v
NAME                	PROC_NAME           	OWNER   	DATE              	COMMITTED	UUID                                    	TAGS
# dsdt cat
['/root/.disdat/context/mycontext/objects/fde8963b-f3c5-48e0-93f7-52bbfa5c3f0b/hello_data.csv']
```

The output doesn't look like the one in README.rst, but perhaps I'm not running this correctly? I verified I have access to the public files on S3.

Really interesting work, and I'm excited to make it run 😄

**Comment by kyocum** [comment]
Actually, everything worked fine!   

`dsdt add` can make a bundle in two ways.  The default is that it will create a bundle containing the files you give it (a file or a directory containing files).    That's what happened above.   

Or `dsdt add -i` will treat a csv or tsv as a "bundle" itself -- a collection of named arrays of literals and files.    

I've updated the simple test drive to reflect this, please let me know if that works!

**Comment by stefano-meschiari** [comment]
Adding the `-i` options works. It still is not listing the bundles correctly (`dsdt cat` shows the objects in the bundle, but `dsdt ls -v` doesn't list bundles).

**Comment by kyocum** [comment]
By default `dsdt ls` will list out the final bundles of a pipeline, those that have an internal tag k:v pair (root_task:True).    In this case, `dsdt add` wasn't adding that tag, so you have to tell it to list out the intermediate bundles too `dsdt ls -iv`, adding the `-i` flag for intermediate.    Having `dsdt ls` by default only list out the final output bundles of pipelines was done to make it possible to look at a much shorter list of bundles.  

We could change `dsdt ls` to always list everything, and have a flag for 'only final outputs'.   Thoughts? 

And if you want to try adding that tag manually you can say `dsdt add -t root_task:True <bundle name> <file>`, after which `dsdt ls` will list out that bundle.   You can also print out all the tags on a bundle with `-p`.

**Comment by kyocum** [comment]
@stefano-meschiari closing this issue.  Feel free to open an additional issue or join our new slack [here](https://join.slack.com/t/disdatworkspace/shared_invite/enQtNjUzMDcxMzc2ODU1LWJhMzgzYWYzYjFlMzQxOTc5NzcyMzFhOTU4YjlkNDYwN2FmOGVkZTNmZjBlMzk3ZjAxZjNhYjc2YzcxNjg4N2Q)
