### ISSUE TITLE
references to 'dsdt checkout' command

### ISSUE THREAD

**Issue by barryhicks** [kyocum/disdat#13]
There are still several messages that reference the 'dsdt checkout' command, which I believe is deprecated:

$ grep -r --include \*.py 'dsdt checkout' .
./build/lib/disdat/fs.py:                    print "No current local context, please change context with 'dsdt checkout'"
./build/lib/disdat/fs.py:            print("Disdat on context {}, please 'dsdt checkout <otherbranch>' before deleting.".format(local_context))
./disdat/fs.py:                    print "No current local context, please change context with 'dsdt checkout'"
./disdat/fs.py:            print("Disdat on context {}, please 'dsdt checkout <otherbranch>' before deleting.".format(local_context))

**Comment by kyocum** [comment]
oops, yes, all those need to be changed to "context".    Good catch.
