### ISSUE TITLE
remove print statements in favor of logging

### ISSUE THREAD

**Issue by jcessna** [kyocum/disdat#183]
although much of disdat output uses python logging, there are still many print statements that make it difficult to filter out unwanted verbose output for users of disdat library

**Comment by kyocum** [comment]
Converted the incremental db built prints to logger statements when doing a pull.   Please comment below on others that might exist.

**Comment by jcessna** [comment]
Pushed committed bundle None uuid d7afdfb1-4db0-4e98-bc3a-4a72a2490754 to remote s3://moonscape-disdat/context
