### ISSUE TITLE
small issue in Disdat Architecture and Design doc

### ISSUE THREAD

**Issue by barryhicks** [kyocum/disdat#8]
Under "Bundle Collections", it says:
● status: Report current context and branch.
● branch: Create a new local branch from some context.
● checkout: Move to a different local branch.
● remote: Attach an s3 path to this local context.
But this doesn't match the text below, which describes "status", "context", "switch" , and "remote" comands.
Is there still such a thing as branches? I don't see it referenced anyplace else in the doc. Maybe there are just contexts?

**Comment by kyocum** [comment]
Oops.  Yes.   I used to have the CLI have a 'branch' and a 'checkout' command.  However, data contexts aren't really branches, so to reduce the confusion I went with 'context' and 'switch'.    I'll fix this soon.

**Comment by kyocum** [comment]
OK, doc fixed.
