### ISSUE TITLE
please add ExamplePipeline.py to examples/pipelines

### ISSUE THREAD

**Issue by barryhicks** [kyocum/disdat#9]
Please add the example from Ken's Vimeo talk (ExamplePipeline.py) to examples/pipelines. It's nice since it's really simple. What worked for me is:

import numpy as np
from disdat.pipe import PipeTask

class GenData(PipeTask):

    def pipe_requires(self, **kwargs):
        self.set_bundle_name("GenData")

    def pipe_run(self, **kwargs):
        return np.array([77, 100, 88])

class Average(PipeTask):

    def pipe_requires(self, **kwargs):
        params = [{}]
        self.add_dependency("my_input_data", GenData, {})

    def pipe_run(self, my_input_data=None, **kwargs):
        print my_input_data, type(my_input_data)
        return {'average' : [np.average(my_input_data)]}

**Comment by kyocum** [comment]
See latest merged PR from kyocum/newexample.
